use_frameworks!

platform :ios, '9.0'

install! 'cocoapods', :deterministic_uuids => false

target 'iosApp' do
    pod 'Kingfisher', '~> 4.0'
    pod 'MaterialComponents'
    pod 'dukecon', :path => '../common/dukecon'
end
