/*
 * DukeCon API
 * Documentation of the DukeCon REST API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.dukecon.android.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Event
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-04-07T21:47:40.050+02:00[Europe/Berlin]")
public class Event {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_START = "start";
  @SerializedName(SERIALIZED_NAME_START)
  private String start;

  public static final String SERIALIZED_NAME_END = "end";
  @SerializedName(SERIALIZED_NAME_END)
  private String end;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_ABSTRACT_TEXT = "abstractText";
  @SerializedName(SERIALIZED_NAME_ABSTRACT_TEXT)
  private String abstractText;

  public static final String SERIALIZED_NAME_DEMO = "demo";
  @SerializedName(SERIALIZED_NAME_DEMO)
  private Boolean demo = false;

  public static final String SERIALIZED_NAME_SIMULTAN = "simultan";
  @SerializedName(SERIALIZED_NAME_SIMULTAN)
  private Boolean simultan = false;

  public static final String SERIALIZED_NAME_VERY_POPULAR = "veryPopular";
  @SerializedName(SERIALIZED_NAME_VERY_POPULAR)
  private Boolean veryPopular = false;

  public static final String SERIALIZED_NAME_FULLY_BOOKED = "fullyBooked";
  @SerializedName(SERIALIZED_NAME_FULLY_BOOKED)
  private Boolean fullyBooked = false;

  public static final String SERIALIZED_NAME_NUMBER_OF_FAVORITES = "numberOfFavorites";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_FAVORITES)
  private Integer numberOfFavorites;

  public static final String SERIALIZED_NAME_TRACK_ID = "trackId";
  @SerializedName(SERIALIZED_NAME_TRACK_ID)
  private String trackId;

  public static final String SERIALIZED_NAME_AUDIENCE_ID = "audienceId";
  @SerializedName(SERIALIZED_NAME_AUDIENCE_ID)
  private String audienceId;

  public static final String SERIALIZED_NAME_TYPE_ID = "typeId";
  @SerializedName(SERIALIZED_NAME_TYPE_ID)
  private String typeId;

  public static final String SERIALIZED_NAME_LOCATION_ID = "locationId";
  @SerializedName(SERIALIZED_NAME_LOCATION_ID)
  private String locationId;

  public static final String SERIALIZED_NAME_SPEAKER_IDS = "speakerIds";
  @SerializedName(SERIALIZED_NAME_SPEAKER_IDS)
  private List<String> speakerIds = null;

  public static final String SERIALIZED_NAME_LANGUAGE_ID = "languageId";
  @SerializedName(SERIALIZED_NAME_LANGUAGE_ID)
  private String languageId;

  public Event id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Event start(String start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @ApiModelProperty(value = "")
  public String getStart() {
    return start;
  }

  public void setStart(String start) {
    this.start = start;
  }

  public Event end(String end) {
    this.end = end;
    return this;
  }

   /**
   * Get end
   * @return end
  **/
  @ApiModelProperty(value = "")
  public String getEnd() {
    return end;
  }

  public void setEnd(String end) {
    this.end = end;
  }

  public Event title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Event abstractText(String abstractText) {
    this.abstractText = abstractText;
    return this;
  }

   /**
   * Get abstractText
   * @return abstractText
  **/
  @ApiModelProperty(value = "")
  public String getAbstractText() {
    return abstractText;
  }

  public void setAbstractText(String abstractText) {
    this.abstractText = abstractText;
  }

  public Event demo(Boolean demo) {
    this.demo = demo;
    return this;
  }

   /**
   * Get demo
   * @return demo
  **/
  @ApiModelProperty(value = "")
  public Boolean isDemo() {
    return demo;
  }

  public void setDemo(Boolean demo) {
    this.demo = demo;
  }

  public Event simultan(Boolean simultan) {
    this.simultan = simultan;
    return this;
  }

   /**
   * Get simultan
   * @return simultan
  **/
  @ApiModelProperty(value = "")
  public Boolean isSimultan() {
    return simultan;
  }

  public void setSimultan(Boolean simultan) {
    this.simultan = simultan;
  }

  public Event veryPopular(Boolean veryPopular) {
    this.veryPopular = veryPopular;
    return this;
  }

   /**
   * Get veryPopular
   * @return veryPopular
  **/
  @ApiModelProperty(value = "")
  public Boolean isVeryPopular() {
    return veryPopular;
  }

  public void setVeryPopular(Boolean veryPopular) {
    this.veryPopular = veryPopular;
  }

  public Event fullyBooked(Boolean fullyBooked) {
    this.fullyBooked = fullyBooked;
    return this;
  }

   /**
   * Get fullyBooked
   * @return fullyBooked
  **/
  @ApiModelProperty(value = "")
  public Boolean isFullyBooked() {
    return fullyBooked;
  }

  public void setFullyBooked(Boolean fullyBooked) {
    this.fullyBooked = fullyBooked;
  }

  public Event numberOfFavorites(Integer numberOfFavorites) {
    this.numberOfFavorites = numberOfFavorites;
    return this;
  }

   /**
   * Get numberOfFavorites
   * @return numberOfFavorites
  **/
  @ApiModelProperty(value = "")
  public Integer getNumberOfFavorites() {
    return numberOfFavorites;
  }

  public void setNumberOfFavorites(Integer numberOfFavorites) {
    this.numberOfFavorites = numberOfFavorites;
  }

  public Event trackId(String trackId) {
    this.trackId = trackId;
    return this;
  }

   /**
   * Get trackId
   * @return trackId
  **/
  @ApiModelProperty(value = "")
  public String getTrackId() {
    return trackId;
  }

  public void setTrackId(String trackId) {
    this.trackId = trackId;
  }

  public Event audienceId(String audienceId) {
    this.audienceId = audienceId;
    return this;
  }

   /**
   * Get audienceId
   * @return audienceId
  **/
  @ApiModelProperty(value = "")
  public String getAudienceId() {
    return audienceId;
  }

  public void setAudienceId(String audienceId) {
    this.audienceId = audienceId;
  }

  public Event typeId(String typeId) {
    this.typeId = typeId;
    return this;
  }

   /**
   * Get typeId
   * @return typeId
  **/
  @ApiModelProperty(value = "")
  public String getTypeId() {
    return typeId;
  }

  public void setTypeId(String typeId) {
    this.typeId = typeId;
  }

  public Event locationId(String locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @ApiModelProperty(value = "")
  public String getLocationId() {
    return locationId;
  }

  public void setLocationId(String locationId) {
    this.locationId = locationId;
  }

  public Event speakerIds(List<String> speakerIds) {
    this.speakerIds = speakerIds;
    return this;
  }

  public Event addSpeakerIdsItem(String speakerIdsItem) {
    if (this.speakerIds == null) {
      this.speakerIds = new ArrayList<String>();
    }
    this.speakerIds.add(speakerIdsItem);
    return this;
  }

   /**
   * Get speakerIds
   * @return speakerIds
  **/
  @ApiModelProperty(value = "")
  public List<String> getSpeakerIds() {
    return speakerIds;
  }

  public void setSpeakerIds(List<String> speakerIds) {
    this.speakerIds = speakerIds;
  }

  public Event languageId(String languageId) {
    this.languageId = languageId;
    return this;
  }

   /**
   * Get languageId
   * @return languageId
  **/
  @ApiModelProperty(value = "")
  public String getLanguageId() {
    return languageId;
  }

  public void setLanguageId(String languageId) {
    this.languageId = languageId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Event event = (Event) o;
    return Objects.equals(this.id, event.id) &&
        Objects.equals(this.start, event.start) &&
        Objects.equals(this.end, event.end) &&
        Objects.equals(this.title, event.title) &&
        Objects.equals(this.abstractText, event.abstractText) &&
        Objects.equals(this.demo, event.demo) &&
        Objects.equals(this.simultan, event.simultan) &&
        Objects.equals(this.veryPopular, event.veryPopular) &&
        Objects.equals(this.fullyBooked, event.fullyBooked) &&
        Objects.equals(this.numberOfFavorites, event.numberOfFavorites) &&
        Objects.equals(this.trackId, event.trackId) &&
        Objects.equals(this.audienceId, event.audienceId) &&
        Objects.equals(this.typeId, event.typeId) &&
        Objects.equals(this.locationId, event.locationId) &&
        Objects.equals(this.speakerIds, event.speakerIds) &&
        Objects.equals(this.languageId, event.languageId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, start, end, title, abstractText, demo, simultan, veryPopular, fullyBooked, numberOfFavorites, trackId, audienceId, typeId, locationId, speakerIds, languageId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Event {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    abstractText: ").append(toIndentedString(abstractText)).append("\n");
    sb.append("    demo: ").append(toIndentedString(demo)).append("\n");
    sb.append("    simultan: ").append(toIndentedString(simultan)).append("\n");
    sb.append("    veryPopular: ").append(toIndentedString(veryPopular)).append("\n");
    sb.append("    fullyBooked: ").append(toIndentedString(fullyBooked)).append("\n");
    sb.append("    numberOfFavorites: ").append(toIndentedString(numberOfFavorites)).append("\n");
    sb.append("    trackId: ").append(toIndentedString(trackId)).append("\n");
    sb.append("    audienceId: ").append(toIndentedString(audienceId)).append("\n");
    sb.append("    typeId: ").append(toIndentedString(typeId)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    speakerIds: ").append(toIndentedString(speakerIds)).append("\n");
    sb.append("    languageId: ").append(toIndentedString(languageId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

